version: "2"
services:
  web:
    container_name: data-findhub-web
    build: .
    environment:
      CELERY_HOST: redis
    networks:
      - data-find-network
    ports:
      - "8000:8000"
    volumes:
      - .:/usr/src/app

  redis:
    image: 'bitnami/redis:latest'
    container_name: data-findhub-redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - data-find-network

networks:
  data-find-network: